package codegen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"text/template"
	"time"

	"github.com/chnxq/xkit/internal/binding"
	"github.com/chnxq/xkit/internal/config"
	"github.com/chnxq/xkit/internal/entschema"
	"github.com/chnxq/xkit/internal/project"
	xproto "github.com/chnxq/xkit/internal/proto"
)

type Options struct {
	DryRun  bool
	Version string
}

type generatedMeta struct {
	Version     string
	GeneratedAt string
}

type templateBase struct {
	Generated generatedMeta
}

type Result struct {
	Written []string
	Skipped []string
}

type Runner struct {
	project      project.Info
	config       config.Config
	protoIndex   map[string]xproto.Service
	bindingIndex map[string]binding.ServiceBinding
	schemaIndex  map[string]entschema.Schema
	options      Options
}

type resourcePlan struct {
	Resource        config.Resource
	Proto           xproto.Service
	Binding         binding.ServiceBinding
	ResourceField   string
	FileBase        string
	APIPackageAlias string
	Schema          entschema.Schema
}

type importSpec struct {
	Alias string
	Path  string
}

type serviceTemplateData struct {
	templateBase
	Imports         []importSpec
	StructName      string
	ConstructorName string
	APIPackageAlias string
	Embeds          []string
	ErrorHelperName string
	Methods         []serviceMethodData
}

type serviceMethodData struct {
	Name           string
	Classification string
	Params         []namedType
	ResponseType   string
}

type namedType struct {
	Name string
	Type string
}

type registerTemplateData struct {
	templateBase
	Imports          []importSpec
	StructName       string
	RegisterFuncName string
	ServerType       string
	Services         []registerServiceData
}

type registerServiceData struct {
	FieldName     string
	Alias         string
	InterfaceName string
	RegisterFunc  string
}

type wireTemplateData struct {
	templateBase
	Imports      []importSpec
	Constructors []string
	Alias        string
	Layer        string
}

type repoTemplateData struct {
	templateBase
	Imports         []importSpec
	RepoName        string
	RepoStructName  string
	ConstructorName string
	EntityName      string
	ResourceName    string
	EntPackage      string
	PredicateType   string
	DTOType         string
	Methods         []repoMethodData
	Fields          []entschema.Field
}

type repoMethodData struct {
	Name           string
	Params         []namedType
	ResponseType   string
	Kind           string
	Setters        []setterData
	ReturnsValue   bool
	IDExpr         string
	ExistField     string
	ViewMaskExpr   string
	ListItemsField string
	ListTotalField string
	ExistsCases    []existsCaseData
	NilReturn      string
	ZeroReturn     string
}

type existsCaseData struct {
	OneofType string
	Predicate string
	ValueExpr string
}

type setterData struct {
	Method string
	Expr   string
}

var aliasPattern = regexp.MustCompile(`\b([A-Za-z_][A-Za-z0-9_]*)\.`)

const serviceFileTemplate = `// Code generated by xkit. DO NOT EDIT.
// xkit version: {{ .Generated.Version }}
// generated at: {{ .Generated.GeneratedAt }}

package service

import (
{{range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{end}}
)

type {{ .StructName }} struct {
{{range .Embeds}}
	{{ . }}
{{end}}
}

func {{ .ConstructorName }}() *{{ .StructName }} {
	return &{{ .StructName }}{}
}

func {{ .ErrorHelperName }}(method string) error {
	return fmt.Errorf("{{ .StructName }}.%s not implemented", method)
}

{{range .Methods}}
// {{ .Name }} is generated from the source proto contract.
// Classification: {{ .Classification }}.
func (s *{{ $.StructName }}) {{ .Name }}({{range $index, $param := .Params}}{{if $index}}, {{end}}{{ $param.Name }} {{ $param.Type }}{{end}}) ({{ .ResponseType }}, error) {
{{range .Params}}
	_ = {{.Name}}
{{end}}

	var out {{ .ResponseType }}
	return out, {{ $.ErrorHelperName }}("{{ .Name }}")
}

{{end}}`

const serviceExtTemplate = `package service

// Add {{ .StructName }}-specific hooks and helpers here.
// This file is created once and is never overwritten by xkit.
`

const registerFileTemplate = `// Code generated by xkit. DO NOT EDIT.
// xkit version: {{ .Generated.Version }}
// generated at: {{ .Generated.GeneratedAt }}

package server

import (
{{range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{end}}
)

type {{ .StructName }} struct {
{{range .Services}}
	{{ .FieldName }} {{ .Alias }}.{{ .InterfaceName }}
{{end}}
}

func {{ .RegisterFuncName }}(srv {{ .ServerType }}, services {{ .StructName }}) {
{{range .Services}}
	if services.{{ .FieldName }} != nil {
		{{ .Alias }}.{{ .RegisterFunc }}(srv, services.{{ .FieldName }})
	}
{{end}}
}
`

const wireFileTemplate = `// Code generated by xkit. DO NOT EDIT.
// xkit version: {{ .Generated.Version }}
// generated at: {{ .Generated.GeneratedAt }}

//go:build wireinject
// +build wireinject

//go:generate go run github.com/google/wire/cmd/wire

package providers

import (
{{range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{end}}
)

// ProviderSet is the Wire provider set for {{ .Layer }} layer.
var ProviderSet = wire.NewSet(
{{range .Constructors}}
	{{if $.Alias}}{{ $.Alias }}.{{end}}{{ . }},
{{end}}
)
`

const repoFileTemplate = `// Code generated by xkit. DO NOT EDIT.
// xkit version: {{ .Generated.Version }}
// generated at: {{ .Generated.GeneratedAt }}

package data

import (
{{range .Imports}}
	{{if .Alias}}{{.Alias}} {{end}}"{{.Path}}"
{{end}}
)

type {{ .RepoName }} interface {
{{range .Methods}}
	{{ .Name }}({{range $index, $param := .Params}}{{if $index}}, {{end}}{{ $param.Name }} {{ $param.Type }}{{end}}) ({{ .ResponseType }}, error)
{{end}}
}

type {{ .RepoStructName }} struct {
	entClient *entCrud.EntClient[*ent.Client]
	log       *log.Helper

	mapper *mapper.CopierMapper[{{ .DTOType }}, ent.{{ .EntityName }}]

	repository *entCrud.Repository[
		ent.{{ .EntityName }}Query, ent.{{ .EntityName }}Select,
		ent.{{ .EntityName }}Create, ent.{{ .EntityName }}CreateBulk,
		ent.{{ .EntityName }}Update, ent.{{ .EntityName }}UpdateOne,
		ent.{{ .EntityName }}Delete,
		predicate.{{ .PredicateType }},
		{{ .DTOType }}, ent.{{ .EntityName }},
	]
}

func {{ .ConstructorName }}(ctx *app.AppCtx, entClient *entCrud.EntClient[*ent.Client]) *{{ .RepoStructName }} {
	repo := &{{ .RepoStructName }}{
		log:       ctx.NewLoggerHelper("{{ .ResourceName }}/data"),
		entClient: entClient,
		mapper:    mapper.NewCopierMapper[{{ .DTOType }}, ent.{{ .EntityName }}](),
	}

	repo.init()

	return repo
}

func (r *{{ .RepoStructName }}) init() {
	r.repository = entCrud.NewRepository[
		ent.{{ .EntityName }}Query, ent.{{ .EntityName }}Select,
		ent.{{ .EntityName }}Create, ent.{{ .EntityName }}CreateBulk,
		ent.{{ .EntityName }}Update, ent.{{ .EntityName }}UpdateOne,
		ent.{{ .EntityName }}Delete,
		predicate.{{ .PredicateType }},
		{{ .DTOType }}, ent.{{ .EntityName }},
	](r.mapper)

	r.mapper.AppendConverters(copierutil.NewTimeStringConverterPair())
	r.mapper.AppendConverters(copierutil.NewTimeTimestamppbConverterPair())
}

{{range .Methods}}
// {{ .Name }} is generated from the source proto contract.
func (r *{{ $.RepoStructName }}) {{ .Name }}({{range $index, $param := .Params}}{{if $index}}, {{end}}{{ $param.Name }} {{ $param.Type }}{{end}}) ({{ .ResponseType }}, error) {
{{if eq .Kind "create"}}
	if req == nil || req.Data == nil {
		return {{ .ZeroReturn }}, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().{{ $.EntityName }}.Create()
{{range .Setters}}
	builder.{{ .Method }}({{ .Expr }})
{{end}}

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("insert {{ $.ResourceName }} failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}

{{if .ReturnsValue}}
	return r.mapper.ToDTO(entity), nil
{{else}}
	_ = entity
	return {{ .NilReturn }}, nil
{{end}}
{{else if eq .Kind "update"}}
	if req == nil || req.Data == nil {
		return {{ .ZeroReturn }}, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().{{ $.EntityName }}.UpdateOneID(req.GetId())
{{range .Setters}}
	builder.{{ .Method }}({{ .Expr }})
{{end}}

	entity, err := builder.Save(ctx)
	if err != nil {
		r.log.Errorf("update {{ $.ResourceName }} failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}

{{if .ReturnsValue}}
	return r.mapper.ToDTO(entity), nil
{{else}}
	_ = entity
	return {{ .NilReturn }}, nil
{{end}}
{{else if eq .Kind "delete"}}
	if req == nil {
		return {{ .ZeroReturn }}, fmt.Errorf("invalid parameter")
	}

	if err := r.entClient.Client().{{ $.EntityName }}.DeleteOneID({{ .IDExpr }}).Exec(ctx); err != nil {
		r.log.Errorf("delete {{ $.ResourceName }} failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}

	return {{ .NilReturn }}, nil
{{else if eq .Kind "exists"}}
	if req == nil {
		return {{ .ZeroReturn }}, fmt.Errorf("invalid parameter")
	}

	exist, err := r.entClient.Client().{{ $.EntityName }}.Query().Where({{ $.EntPackage }}.IDEQ({{ .IDExpr }})).Exist(ctx)
	if err != nil {
		r.log.Errorf("query {{ $.ResourceName }} exists failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}

	return &{{ .ResponseType | trimPointer }}{ {{ .ExistField }}: exist }, nil
{{else if eq .Kind "query_exists"}}
	if req == nil {
		return {{ .ZeroReturn }}, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().{{ $.EntityName }}.Query()
	switch req.GetQueryBy().(type) {
{{range .ExistsCases}}
	case *{{ .OneofType }}:
		builder.Where({{ $.EntPackage }}.{{ .Predicate }}({{ .ValueExpr }}))
{{end}}
	default:
		return &{{ .ResponseType | trimPointer }}{ {{ .ExistField }}: false }, fmt.Errorf("invalid query by type")
	}

	exist, err := builder.Exist(ctx)
	if err != nil {
		r.log.Errorf("query {{ $.ResourceName }} exists failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}

	return &{{ .ResponseType | trimPointer }}{ {{ .ExistField }}: exist }, nil
{{else if eq .Kind "get"}}
	if req == nil {
		return {{ .ZeroReturn }}, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().{{ $.EntityName }}.Query()
	entity, err := builder.Where({{ $.EntPackage }}.IDEQ({{ .IDExpr }})).Only(ctx)
	if err != nil {
		r.log.Errorf("get {{ $.ResourceName }} failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}

	return r.mapper.ToDTO(entity), nil
{{else if eq .Kind "list"}}
	if req == nil {
		return {{ .ZeroReturn }}, fmt.Errorf("invalid parameter")
	}

	builder := r.entClient.Client().{{ $.EntityName }}.Query()
	total, err := builder.Clone().Count(ctx)
	if err != nil {
		r.log.Errorf("count {{ $.ResourceName }} failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}
	limit := int(req.GetLimit())
	if limit <= 0 {
		limit = 20
	}
	entities, err := builder.Limit(limit).Offset(int(req.GetOffset())).All(ctx)
	if err != nil {
		r.log.Errorf("list {{ $.ResourceName }} failed: %s", err.Error())
		return {{ .ZeroReturn }}, err
	}

	items := make([]*{{ $.DTOType }}, 0, len(entities))
	for _, entity := range entities {
		items = append(items, r.mapper.ToDTO(entity))
	}

	return &{{ .ResponseType | trimPointer }}{ {{ .ListTotalField }}: uint64(total), {{ .ListItemsField }}: items }, nil
{{else}}
{{range .Params}}
	_ = {{.Name}}
{{end}}

	var out {{ .ResponseType }}
	return out, fmt.Errorf("{{ $.RepoName }}.{{ .Name }} not implemented")
{{end}}
}

{{end}}
`

func New(info project.Info, cfg config.Config, options Options) (*Runner, error) {
	if cfg.Module != "" && cfg.Module != info.Module {
		return nil, fmt.Errorf("config module %q does not match target project module %q", cfg.Module, info.Module)
	}

	protoIndex, err := xproto.LoadServices(info.Root)
	if err != nil {
		return nil, err
	}

	bindingIndex, err := binding.Load(info.Root, info.Module)
	if err != nil {
		return nil, err
	}

	schemaIndex, err := entschema.Load(info.Root)
	if err != nil {
		return nil, err
	}

	return &Runner{
		project:      info,
		config:       cfg,
		protoIndex:   protoIndex,
		bindingIndex: bindingIndex,
		schemaIndex:  schemaIndex,
		options:      options,
	}, nil
}

func (r *Runner) Generate(target string) (Result, error) {
	switch target {
	case "service":
		return r.generateServiceFiles()
	case "repo":
		return r.generateRepoFiles()
	case "register":
		return r.generateRegisterFiles()
	case "wire":
		return r.generateWireFiles()
	case "all":
		return r.generateAll()
	default:
		return Result{}, fmt.Errorf("unknown generation target %q", target)
	}
}

func (r *Runner) generateAll() (Result, error) {
	var result Result
	parts := []string{"service", "repo", "register", "wire"}
	for _, part := range parts {
		partResult, err := r.Generate(part)
		if err != nil {
			return result, err
		}
		result.Written = append(result.Written, partResult.Written...)
		result.Skipped = append(result.Skipped, partResult.Skipped...)
	}
	return result, nil
}

func (r *Runner) generateServiceFiles() (Result, error) {
	plans, err := r.plans()
	if err != nil {
		return Result{}, err
	}

	var result Result
	for _, plan := range plans {
		if !plan.Resource.Generate.EffectiveServiceStub() {
			continue
		}

		content, err := r.renderServiceFile(plan)
		if err != nil {
			return result, err
		}

		servicePath := filepath.Join(
			r.project.Root,
			"app",
			r.config.Service,
			"service",
			"internal",
			"service",
			plan.FileBase+"_service.gen.go",
		)
		if err := r.writeGeneratedFile(servicePath, content, &result); err != nil {
			return result, err
		}

		extContent, err := renderTemplate(serviceExtTemplate, map[string]string{
			"StructName": plan.Binding.ServiceName,
		})
		if err != nil {
			return result, err
		}

		extPath := filepath.Join(
			r.project.Root,
			"app",
			r.config.Service,
			"service",
			"internal",
			"service",
			plan.FileBase+"_service_ext.go",
		)
		if err := r.writeExtensionFile(extPath, extContent, &result); err != nil {
			return result, err
		}
	}

	return result, nil
}

func (r *Runner) generateRepoFiles() (Result, error) {
	plans, err := r.plans()
	if err != nil {
		return Result{}, err
	}

	var result Result
	for _, plan := range plans {
		if !plan.Resource.Generate.EffectiveRepoCRUD() {
			continue
		}

		content, err := r.renderRepoFile(plan)
		if err != nil {
			return result, err
		}

		repoPath := filepath.Join(
			r.project.Root,
			"app",
			r.config.Service,
			"service",
			"internal",
			"data",
			plan.FileBase+"_repo.gen.go",
		)
		if err := r.writeGeneratedFile(repoPath, content, &result); err != nil {
			return result, err
		}
	}

	return result, nil
}

func (r *Runner) generateRegisterFiles() (Result, error) {
	plans, err := r.plans()
	if err != nil {
		return Result{}, err
	}

	var httpServices []registerServiceData
	var grpcServices []registerServiceData
	httpImports := []importSpec{{Alias: "httptransport", Path: "github.com/chnxq/xkitpkg/transport/http"}}
	grpcImports := []importSpec{{Path: "google.golang.org/grpc"}}

	for _, plan := range plans {
		if plan.Resource.Generate.EffectiveRestRegister() {
			httpServices = append(httpServices, registerServiceData{
				FieldName:     plan.ResourceField,
				Alias:         plan.APIPackageAlias,
				InterfaceName: plan.Binding.ServiceName + "HTTPServer",
				RegisterFunc:  "Register" + plan.Binding.ServiceName + "HTTPServer",
			})
			httpImports = append(httpImports, importSpec{Alias: plan.APIPackageAlias, Path: plan.Binding.ImportPath})
		}

		if plan.Resource.Generate.EffectiveGRPCRegister() {
			grpcServices = append(grpcServices, registerServiceData{
				FieldName:     plan.ResourceField,
				Alias:         plan.APIPackageAlias,
				InterfaceName: plan.Binding.ServiceName + "Server",
				RegisterFunc:  "Register" + plan.Binding.ServiceName + "Server",
			})
			grpcImports = append(grpcImports, importSpec{Alias: plan.APIPackageAlias, Path: plan.Binding.ImportPath})
		}
	}

	var result Result
	if len(httpServices) > 0 {
		httpContent, err := renderTemplate(registerFileTemplate, registerTemplateData{
			templateBase:     r.templateBase(),
			Imports:          uniqueImports(httpImports),
			StructName:       "GeneratedHTTPServices",
			RegisterFuncName: "RegisterGeneratedHTTPServices",
			ServerType:       "*httptransport.Server",
			Services:         httpServices,
		})
		if err != nil {
			return result, err
		}

		httpPath := filepath.Join(
			r.project.Root,
			"app",
			r.config.Service,
			"service",
			"internal",
			"server",
			"rest_register.gen.go",
		)
		if err := r.writeGeneratedFile(httpPath, httpContent, &result); err != nil {
			return result, err
		}
	}

	if len(grpcServices) > 0 {
		grpcContent, err := renderTemplate(registerFileTemplate, registerTemplateData{
			templateBase:     r.templateBase(),
			Imports:          uniqueImports(grpcImports),
			StructName:       "GeneratedGRPCServices",
			RegisterFuncName: "RegisterGeneratedGRPCServices",
			ServerType:       "grpc.ServiceRegistrar",
			Services:         grpcServices,
		})
		if err != nil {
			return result, err
		}

		grpcPath := filepath.Join(
			r.project.Root,
			"app",
			r.config.Service,
			"service",
			"internal",
			"server",
			"grpc_register.gen.go",
		)
		if err := r.writeGeneratedFile(grpcPath, grpcContent, &result); err != nil {
			return result, err
		}
	}

	return result, nil
}

func (r *Runner) generateWireFiles() (Result, error) {
	plans, err := r.plans()
	if err != nil {
		return Result{}, err
	}

	var constructors []string
	for _, plan := range plans {
		if !plan.Resource.Generate.EffectiveWire() || !plan.Resource.Generate.EffectiveServiceStub() {
			continue
		}
		constructors = append(constructors, "New"+plan.Binding.ServiceName)
	}

	serviceImports := []importSpec{{Path: "github.com/google/wire"}}
	if len(constructors) > 0 {
		serviceImports = append(serviceImports, importSpec{
			Alias: "servicepkg",
			Path: filepath.ToSlash(filepath.Join(
				r.project.Module,
				"app",
				r.config.Service,
				"service",
				"internal",
				"service",
			)),
		})
	}

	serviceWireContent, err := renderTemplate(wireFileTemplate, wireTemplateData{
		templateBase: r.templateBase(),
		Imports:      serviceImports,
		Constructors: constructors,
		Alias:        "servicepkg",
		Layer:        "service",
	})
	if err != nil {
		return Result{}, err
	}

	dataWireContent, err := renderTemplate(wireFileTemplate, wireTemplateData{
		templateBase: r.templateBase(),
		Imports:      []importSpec{{Path: "github.com/google/wire"}},
		Constructors: nil,
		Layer:        "data",
	})
	if err != nil {
		return Result{}, err
	}

	var result Result
	serviceWirePath := filepath.Join(
		r.project.Root,
		"app",
		r.config.Service,
		"service",
		"internal",
		"service",
		"providers",
		"wire_set.gen.go",
	)
	if err := r.writeGeneratedFile(serviceWirePath, serviceWireContent, &result); err != nil {
		return result, err
	}

	dataWirePath := filepath.Join(
		r.project.Root,
		"app",
		r.config.Service,
		"service",
		"internal",
		"data",
		"providers",
		"wire_set.gen.go",
	)
	if err := r.writeGeneratedFile(dataWirePath, dataWireContent, &result); err != nil {
		return result, err
	}

	return result, nil
}

func (r *Runner) plans() ([]resourcePlan, error) {
	var plans []resourcePlan
	for _, resource := range r.config.Resources {
		protoService, ok := r.protoIndex[resource.ProtoService]
		if !ok {
			return nil, fmt.Errorf("proto service %q not found under api/protos", resource.ProtoService)
		}

		bindingService, ok := r.bindingIndex[resource.ProtoService]
		if !ok {
			return nil, fmt.Errorf("binding service %q not found under api/gen", resource.ProtoService)
		}

		entityName := strings.TrimSpace(resource.Entity)
		if entityName == "" {
			entityName = strings.TrimSuffix(bindingService.ServiceName, "Service")
		}
		schema, ok := r.schemaIndex[entityName]
		if !ok && resource.Generate.EffectiveRepoCRUD() {
			return nil, fmt.Errorf("ent schema %q not found under internal/data/ent/schema", entityName)
		}

		plans = append(plans, resourcePlan{
			Resource:        resource,
			Proto:           protoService,
			Binding:         bindingService,
			ResourceField:   toPascal(resource.Name),
			FileBase:        resource.Name,
			APIPackageAlias: apiAlias(bindingService.ImportPath),
			Schema:          schema,
		})
	}

	return plans, nil
}

func (r *Runner) renderServiceFile(plan resourcePlan) ([]byte, error) {
	imports := []importSpec{
		{Alias: plan.APIPackageAlias, Path: plan.Binding.ImportPath},
		{Path: "fmt"},
	}

	usedAliases := make(map[string]struct{})
	for _, method := range plan.Binding.Methods {
		for _, typeText := range append(slices.Clone(method.Params), method.Results...) {
			for _, alias := range aliasesInType(typeText) {
				usedAliases[alias] = struct{}{}
			}
		}
	}

	for alias := range usedAliases {
		path, ok := plan.Binding.Imports[alias]
		if !ok {
			continue
		}
		imports = append(imports, importSpec{Alias: alias, Path: path})
	}

	data := serviceTemplateData{
		templateBase:    r.templateBase(),
		Imports:         uniqueImports(imports),
		StructName:      plan.Binding.ServiceName,
		ConstructorName: "New" + plan.Binding.ServiceName,
		APIPackageAlias: plan.APIPackageAlias,
		Embeds:          serviceEmbeds(plan.APIPackageAlias, plan.Binding.ServiceName),
		ErrorHelperName: lowerFirst(plan.Binding.ServiceName) + "MethodNotImplemented",
	}

	for _, method := range plan.Binding.Methods {
		classification := lookupClassification(plan.Proto.Methods, method.Name)
		data.Methods = append(data.Methods, serviceMethodData{
			Name:           method.Name,
			Classification: classification,
			Params:         nameParams(method.Params),
			ResponseType:   firstResult(method.Results),
		})
	}

	return renderTemplate(serviceFileTemplate, data)
}

func (r *Runner) renderRepoFile(plan resourcePlan) ([]byte, error) {
	entityName := strings.TrimSpace(plan.Resource.Entity)
	if entityName == "" {
		entityName = plan.Binding.ServiceName
		entityName = strings.TrimSuffix(entityName, "Service")
	}

	dtoAlias := plan.APIPackageAlias
	dtoImport := plan.Binding.ImportPath
	if strings.TrimSpace(plan.Resource.DTOImport) != "" {
		dtoImport = strings.TrimSpace(plan.Resource.DTOImport)
		dtoAlias = apiAlias(dtoImport)
	}
	dtoName := entityName
	if strings.TrimSpace(plan.Resource.DTOType) != "" {
		dtoName = strings.TrimSpace(plan.Resource.DTOType)
	}
	dtoType := dtoAlias + "." + dtoName
	repoName := strings.TrimSpace(plan.Resource.RepoInterface)
	if repoName == "" {
		repoName = entityName + "Repo"
	}

	imports := []importSpec{
		{Path: "fmt"},
		{Path: "github.com/chnxq/x-crud/entgo", Alias: "entCrud"},
		{Path: "github.com/chnxq/x-utils/copierutil"},
		{Path: "github.com/chnxq/x-utils/mapper"},
		{Path: "github.com/chnxq/xkitmod/log"},
		{Path: "github.com/chnxq/xkitpkg/app"},
		{Path: filepath.ToSlash(filepath.Join(r.project.Module, "internal", "data", "ent"))},
		{Path: filepath.ToSlash(filepath.Join(r.project.Module, "internal", "data", "ent", strings.ToLower(entityName)))},
		{Path: filepath.ToSlash(filepath.Join(r.project.Module, "internal", "data", "ent", "predicate"))},
		{Alias: dtoAlias, Path: dtoImport},
	}
	usedAliases := make(map[string]struct{})
	var methods []repoMethodData
	for _, method := range plan.Binding.Methods {
		if !isCRUDMethod(method.Name) {
			continue
		}
		normalizedParams := normalizeTypeAliases(method.Params, plan.Binding.Imports, dtoImport, dtoAlias)
		normalizedResults := normalizeTypeAliases(method.Results, plan.Binding.Imports, dtoImport, dtoAlias)
		methodData := repoMethodData{
			Name:           method.Name,
			Params:         nameParams(normalizedParams),
			ResponseType:   firstResult(normalizedResults),
			Kind:           repoMethodKind(method.Name),
			Setters:        repoSetters(plan.Schema.Fields, method.Name),
			ReturnsValue:   firstResult(normalizedResults) == "*"+dtoType,
			IDExpr:         "req.GetId()",
			ExistField:     "Exist",
			ViewMaskExpr:   "req.GetViewMask()",
			ListItemsField: "Items",
			ListTotalField: "Total",
			ExistsCases:    existsCases(dtoAlias, requestParamType(normalizedParams), plan.Resource.ExistsFields),
			NilReturn:      nilReturn(firstResult(normalizedResults)),
			ZeroReturn:     zeroReturn(firstResult(normalizedResults)),
		}
		methods = append(methods, methodData)

		for _, typeText := range append(slices.Clone(normalizedParams), normalizedResults...) {
			for _, alias := range aliasesInType(typeText) {
				usedAliases[alias] = struct{}{}
			}
		}
	}
	for alias := range usedAliases {
		path, ok := plan.Binding.Imports[alias]
		if !ok {
			continue
		}
		imports = append(imports, importSpec{Alias: alias, Path: path})
	}

	data := repoTemplateData{
		templateBase:    r.templateBase(),
		Imports:         uniqueImports(imports),
		RepoName:        repoName,
		RepoStructName:  lowerFirst(repoName),
		ConstructorName: "New" + repoName,
		EntityName:      entityName,
		ResourceName:    plan.Resource.Name,
		EntPackage:      strings.ToLower(entityName),
		PredicateType:   entityName,
		DTOType:         dtoType,
		Fields:          plan.Schema.Fields,
	}
	data.Methods = methods

	return renderTemplate(repoFileTemplate, data)
}

func (r *Runner) writeGeneratedFile(path string, content []byte, result *Result) error {
	return r.writeFile(path, content, result, false)
}

func (r *Runner) templateBase() templateBase {
	return templateBase{
		Generated: generatedMeta{
			Version:     r.version(),
			GeneratedAt: time.Now().Format("2006-01-02 15:04:05 MST"),
		},
	}
}

func (r *Runner) version() string {
	if strings.TrimSpace(r.options.Version) == "" {
		return "dev"
	}
	return r.options.Version
}

func (r *Runner) writeExtensionFile(path string, content []byte, result *Result) error {
	return r.writeFile(path, content, result, true)
}

func (r *Runner) writeFile(path string, content []byte, result *Result, skipIfExists bool) error {
	if skipIfExists {
		if _, err := os.Stat(path); err == nil {
			result.Skipped = append(result.Skipped, path)
			return nil
		} else if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("stat %s: %w", path, err)
		}
	}

	if r.options.DryRun {
		result.Written = append(result.Written, path)
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	result.Written = append(result.Written, path)
	return nil
}

func renderTemplate(source string, data any) ([]byte, error) {
	tmpl, err := template.New("file").Funcs(template.FuncMap{
		"trimPointer": trimPointer,
	}).Parse(source)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func uniqueImports(imports []importSpec) []importSpec {
	seen := make(map[string]struct{})
	var out []importSpec
	for _, spec := range imports {
		key := spec.Alias + "|" + spec.Path
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, spec)
	}
	slices.SortFunc(out, func(a, b importSpec) int {
		if a.Path == b.Path {
			return strings.Compare(a.Alias, b.Alias)
		}
		return strings.Compare(a.Path, b.Path)
	})
	return out
}

func aliasesInType(typeText string) []string {
	matches := aliasPattern.FindAllStringSubmatch(typeText, -1)
	aliases := make([]string, 0, len(matches))
	seen := make(map[string]struct{})
	for _, match := range matches {
		if len(match) != 2 {
			continue
		}
		alias := match[1]
		if _, ok := seen[alias]; ok {
			continue
		}
		seen[alias] = struct{}{}
		aliases = append(aliases, alias)
	}
	return aliases
}

func apiAlias(importPath string) string {
	parts := strings.Split(importPath, "/")
	if len(parts) >= 2 && parts[len(parts)-1] == "v1" {
		return sanitizeIdentifier(parts[len(parts)-2] + "v1")
	}
	return sanitizeIdentifier(parts[len(parts)-1])
}

func serviceEmbeds(alias, serviceName string) []string {
	return []string{
		alias + "." + serviceName + "HTTPServer",
		alias + ".Unimplemented" + serviceName + "Server",
	}
}

func isCRUDMethod(name string) bool {
	switch name {
	case "List", "Get", "Create", "Update", "Delete", "Count", "Exists":
		return true
	}
	return strings.HasSuffix(name, "Exists") || strings.HasPrefix(name, "Count")
}

func repoMethodKind(name string) string {
	switch {
	case name == "Create":
		return "create"
	case name == "Update":
		return "update"
	case name == "Delete":
		return "delete"
	case name == "Exists":
		return "exists"
	case strings.HasSuffix(name, "Exists"):
		return "query_exists"
	default:
		return strings.ToLower(name)
	}
}

func existsCases(alias, requestType string, fields []string) []existsCaseData {
	requestName := trimPointer(requestType)
	if requestName == "" || requestName == requestType {
		return nil
	}
	requestName = strings.TrimPrefix(requestName, alias+".")

	fieldNames := map[string]struct{}{}
	for _, field := range fields {
		field = strings.TrimSpace(field)
		if field != "" {
			fieldNames[field] = struct{}{}
		}
	}

	var cases []existsCaseData
	for fieldName := range fieldNames {
		protoName := toPascal(fieldName)
		goName := toGoName(fieldName)
		getterName := protoName
		predicateName := goName
		if fieldName == "id" {
			predicateName = "ID"
		}
		cases = append(cases, existsCaseData{
			OneofType: alias + "." + requestName + "_" + protoName,
			Predicate: predicateName + "EQ",
			ValueExpr: "req.Get" + getterName + "()",
		})
	}
	slices.SortFunc(cases, func(a, b existsCaseData) int {
		if strings.HasSuffix(a.OneofType, "_Id") {
			return -1
		}
		if strings.HasSuffix(b.OneofType, "_Id") {
			return 1
		}
		return strings.Compare(a.OneofType, b.OneofType)
	})
	return cases
}

func requestParamType(types []string) string {
	if len(types) >= 2 {
		return types[1]
	}
	if len(types) == 1 {
		return types[0]
	}
	return ""
}

func trimPointer(typeText string) string {
	return strings.TrimPrefix(typeText, "*")
}

func nilReturn(typeText string) string {
	if strings.HasPrefix(typeText, "*") || strings.HasPrefix(typeText, "[]") || typeText == "any" || typeText == "interface{}" {
		return "nil"
	}
	return zeroReturn(typeText)
}

func zeroReturn(typeText string) string {
	if strings.HasPrefix(typeText, "*") || strings.HasPrefix(typeText, "[]") || typeText == "any" || typeText == "interface{}" {
		return "nil"
	}
	switch typeText {
	case "bool":
		return "false"
	case "string":
		return "\"\""
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
		return "0"
	default:
		return typeText + "{}"
	}
}

func normalizeTypeAliases(types []string, imports map[string]string, targetImport, targetAlias string) []string {
	out := make([]string, 0, len(types))
	for _, typeText := range types {
		normalized := typeText
		for alias, importPath := range imports {
			if importPath != targetImport || alias == targetAlias {
				continue
			}
			normalized = strings.ReplaceAll(normalized, alias+".", targetAlias+".")
		}
		out = append(out, normalized)
	}
	return out
}

func repoSetters(fields []entschema.Field, methodName string) []setterData {
	setters := make([]setterData, 0, len(fields))
	for _, field := range fields {
		if field.Name == "id" || field.Kind == "Enum" || field.Kind == "Time" {
			continue
		}
		if methodName == "Update" && field.Immutable {
			continue
		}
		entName := toGoName(field.Name)
		dtoName := toPascal(field.Name)
		method := "SetNillable" + entName
		setters = append(setters, setterData{
			Method: method,
			Expr:   "req.Data." + dtoName,
		})
	}
	return setters
}

func sanitizeIdentifier(value string) string {
	value = strings.ReplaceAll(value, "_", "")
	value = strings.ReplaceAll(value, "-", "")
	if value == "" {
		return "pkg"
	}
	return value
}

func toPascal(value string) string {
	if value == "" {
		return ""
	}
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	for index, part := range parts {
		if part == "" {
			continue
		}
		parts[index] = strings.ToUpper(part[:1]) + strings.ToLower(part[1:])
	}
	return strings.Join(parts, "")
}

func toGoName(value string) string {
	name := toPascal(value)
	initialisms := map[string]string{
		"Id":  "ID",
		"Ip":  "IP",
		"Url": "URL",
		"Uri": "URI",
	}
	for old, replacement := range initialisms {
		name = strings.ReplaceAll(name, old, replacement)
	}
	return name
}

func lowerFirst(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToLower(value[:1]) + value[1:]
}

func nameParams(types []string) []namedType {
	params := make([]namedType, 0, len(types))
	for index, typeText := range types {
		name := fmt.Sprintf("arg%d", index)
		if index == 0 && typeText == "context.Context" {
			name = "ctx"
		}
		if index == 1 {
			name = "req"
		}
		params = append(params, namedType{
			Name: name,
			Type: typeText,
		})
	}
	return params
}

func firstResult(results []string) string {
	if len(results) == 0 {
		return "any"
	}
	return results[0]
}

func lookupClassification(methods []xproto.Method, name string) string {
	for _, method := range methods {
		if method.Name == name {
			return method.Classification
		}
	}
	return "special"
}
