package codegen

import (
	"path/filepath"
	"strings"

	codegentemplate "github.com/chnxq/xkit/internal/codegen/template"
)

func (r *Runner) generateFrontendHostPageFiles() (Result, error) {
	plans, err := r.plans()
	if err != nil {
		return Result{}, err
	}

	typeScriptRoot, err := resolveTypeScriptRoot(r.project.Root, r.options.TypeScriptRoot)
	if err != nil {
		return Result{}, err
	}
	baseDir := filepath.Join(typeScriptRoot, "apps", "web-antd", "src", "views")

	var result Result
	for _, plan := range plans {
		if !r.supportsStandardFrontendProvider(plan) {
			continue
		}
		if !r.isModuleMode() {
			continue
		}

		data := r.frontendHostPageData(plan)
		content, err := renderAnyTemplate(codegentemplate.FrontendPage, data)
		if err != nil {
			return result, err
		}

		hostViewDir := filepath.Dir(filepath.FromSlash(plan.Resource.Frontend.ViewPath))
		if hostViewDir == "." {
			hostViewDir = ""
		}
		targetPath := filepath.Join(baseDir, r.templateBase().Frontend, hostViewDir, "index.vue")
		if err := r.writeFile(targetPath, content, &result, true); err != nil {
			return result, err
		}
	}

	return result, nil
}

func (r *Runner) frontendHostPageData(plan resourcePlan) frontendPageTemplateData {
	data := r.frontendPageData(plan)
	viewPath := strings.TrimSpace(plan.Resource.Frontend.ViewPath)
	data.HeaderComment = "Code generated by xkit. Generate only once"
	data.ProviderImportPath = "#/views/generated/" + r.templateBase().Frontend + "/" + viewPath + ".provider"
	data.MetaImportPath = "#/views/generated/" + r.templateBase().Frontend + "/" + viewPath + ".meta"
	data.DefineOptionsName = strings.ReplaceAll(plan.ResourceField, ".", "") + "HostPage"
	return data
}
