package codegen

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	codegentemplate "github.com/chnxq/xkit/internal/codegen/template"
)

type frontendPageTemplateData struct {
	templateBase
	EntityType         string
	HeaderComment      string
	ProviderBaseName   string
	MetaBaseName       string
	ProviderImportPath string
	MetaImportPath     string
	DefineOptionsName  string
	ListFuncName       string
	GetFuncName        string
	CreateFuncName     string
	UpdateFuncName     string
	DeleteFuncName     string
	GridClassName      string
	PageTitleKey       string
	PageModuleNameKey  string
	ExportEnabled      bool
	ExportFilename     string
	TreeEnabled        bool
	TreeChildrenField  string
	TreeParentField    string
	ProviderFuncs      []string
	RelationRuntimes   []frontendRelationRuntime
	EnumRuntimes       []frontendEnumRuntime
}

type frontendRelationRuntime struct {
	FieldName           string
	FuncName            string
	OptionsVarName      string
	OptionsMapVarName   string
	PlaceholderKey      string
	ResolveFuncName     string
	SearchPatchFuncName string
	DialogPatchFuncName string
}

type frontendEnumRuntime struct {
	FieldName       string
	TextMapVarName  string
	ResolveFuncName string
	EnumItems       []frontendEnumRuntimeItem
}

type frontendEnumRuntimeItem struct {
	Key     string
	I18nKey string
}

func (r *Runner) generateFrontendPageFiles() (Result, error) {
	plans, err := r.plans()
	if err != nil {
		return Result{}, err
	}

	baseDir := r.frontendGeneratedPageRoot()
	if baseDir == "" {
		return Result{}, fmt.Errorf("resolve frontend page root failed")
	}

	var result Result
	for _, plan := range plans {
		if !r.supportsStandardFrontendProvider(plan) {
			continue
		}
		data := r.frontendPageData(plan)
		content, err := renderAnyTemplate(codegentemplate.FrontendPage, data)
		if err != nil {
			return result, err
		}
		targetPath := filepath.Join(baseDir, filepath.FromSlash(plan.Resource.Frontend.ViewPath+".crud.vue"))
		if r.isModuleMode() {
			viewDir := filepath.Dir(filepath.FromSlash(plan.Resource.Frontend.ViewPath))
			if viewDir == "." {
				viewDir = ""
			}
			targetPath = filepath.Join(baseDir, viewDir, "index.vue")
		}
		if err := r.writeGeneratedFile(targetPath, content, &result); err != nil {
			return result, err
		}
	}

	return result, nil
}

func (r *Runner) frontendPageData(plan resourcePlan) frontendPageTemplateData {
	resourceField := plan.ResourceField
	viewPath := strings.TrimSpace(plan.Resource.Frontend.ViewPath)
	pageModuleNameKey := strings.TrimSpace(plan.Resource.Frontend.I18nPrefix) + ".moduleName"
	if strings.TrimSpace(plan.Resource.Frontend.I18nPrefix) == "" {
		pageModuleNameKey = "page." + lowerFirst(resourceField) + ".moduleName"
	}
	pageTitleKey := pageModuleNameKey

	providerImportPath := "./" + filepath.Base(viewPath) + ".provider"
	metaImportPath := "./" + filepath.Base(viewPath) + ".meta"
	if r.isModuleMode() {
		providerImportPath = filepath.ToSlash(frontendModuleRelativeImport(viewPath, filepath.Join("provider", filepath.Base(viewPath)+".provider")))
		metaImportPath = filepath.ToSlash(frontendModuleRelativeImport(viewPath, filepath.Join("meta", filepath.Base(viewPath)+".meta")))
	}

	return frontendPageTemplateData{
		templateBase:       r.templateBase(),
		EntityType:         "Admin" + resourceField,
		HeaderComment:      "Code generated by xkit. DO NOT EDIT.",
		ProviderBaseName:   filepath.Base(viewPath),
		MetaBaseName:       filepath.Base(viewPath),
		ProviderImportPath: providerImportPath,
		MetaImportPath:     metaImportPath,
		ListFuncName:       "list" + resourceField + "Page",
		GetFuncName:        "get" + resourceField + "ById",
		CreateFuncName:     "create" + resourceField,
		UpdateFuncName:     "update" + resourceField,
		DeleteFuncName:     "delete" + resourceField,
		GridClassName:      "generated-" + frontendSnakeCase(resourceField) + "-grid",
		PageTitleKey:       pageTitleKey,
		PageModuleNameKey:  pageModuleNameKey,
		ExportEnabled:      plan.Resource.Operations["export"],
		ExportFilename:     r.frontendExportFilename(plan),
		TreeEnabled:        plan.Resource.Tree != nil,
		TreeChildrenField:  r.frontendTreeChildrenField(plan),
		TreeParentField:    r.frontendTreeParentField(plan),
		ProviderFuncs:      r.frontendProviderFuncs(plan),
		RelationRuntimes:   r.frontendRelationRuntimes(plan),
		EnumRuntimes:       r.frontendEnumRuntimes(plan),
	}
}

func (r *Runner) frontendProviderFuncs(plan resourcePlan) []string {
	funcs := []string{
		"create" + plan.ResourceField,
		"delete" + plan.ResourceField,
		"get" + plan.ResourceField + "ById",
		"list" + plan.ResourceField + "Page",
		"update" + plan.ResourceField,
	}
	for _, runtime := range r.frontendRelationRuntimes(plan) {
		funcs = append(funcs, runtime.FuncName)
	}
	slices.Sort(funcs)
	return funcs
}

func (r *Runner) frontendExportFilename(plan resourcePlan) string {
	if !r.isModuleMode() {
		return strings.ReplaceAll(strings.TrimSpace(plan.Resource.Name), "_", "-")
	}
	moduleName := strings.TrimSpace(r.options.ModuleName)
	resourceName := strings.ReplaceAll(strings.TrimSpace(plan.Resource.Name), "_", "-")
	if moduleName == "" {
		return resourceName
	}
	if resourceName == "" {
		return moduleName
	}
	return moduleName + "-" + resourceName
}

func frontendModuleRelativeImport(viewPath, targetPath string) string {
	viewDir := filepath.Dir(filepath.FromSlash(viewPath))
	if viewDir == "." {
		viewDir = ""
	}
	fromDir := filepath.Join("views", viewDir)
	rel, err := filepath.Rel(fromDir, targetPath)
	if err != nil {
		return "./" + filepath.ToSlash(targetPath)
	}
	rel = filepath.ToSlash(rel)
	if strings.HasPrefix(rel, ".") {
		return rel
	}
	return "./" + rel
}

func (r *Runner) frontendRelationRuntimes(plan resourcePlan) []frontendRelationRuntime {
	if plan.Resource.Frontend == nil || plan.Resource.Frontend.List == nil {
		return nil
	}
	seen := map[string]struct{}{}
	var items []frontendRelationRuntime
	for _, column := range plan.Resource.Frontend.List.Columns {
		runtime := r.frontendFieldRuntime(plan, column.Field)
		if runtime.Relation == nil {
			continue
		}
		fieldName := runtime.FieldName
		if _, ok := seen[fieldName]; ok {
			continue
		}
		seen[fieldName] = struct{}{}
		relationResourceField := runtime.Relation.ResourceField
		optionsVar := lowerFirst(relationResourceField) + "Options"
		suffix := frontendKeySuffix(fieldName)
		items = append(items, frontendRelationRuntime{
			FieldName:           fieldName,
			FuncName:            "list" + relationResourceField + "Options",
			OptionsVarName:      optionsVar,
			OptionsMapVarName:   optionsVar + "Map",
			PlaceholderKey:      runtime.Relation.PlaceholderKey,
			ResolveFuncName:     "resolve" + suffix + "Label",
			SearchPatchFuncName: "patchSearch" + suffix + "Field",
			DialogPatchFuncName: "patchDialog" + suffix + "Field",
		})
	}
	return items
}

func (r *Runner) frontendEnumRuntimes(plan resourcePlan) []frontendEnumRuntime {
	if plan.Resource.Frontend == nil || plan.Resource.Frontend.List == nil {
		return nil
	}
	seen := map[string]struct{}{}
	var items []frontendEnumRuntime
	for _, column := range plan.Resource.Frontend.List.Columns {
		fieldRuntime := r.frontendFieldRuntime(plan, column.Field)
		if fieldRuntime.Enum == nil {
			continue
		}
		fieldName := fieldRuntime.FieldName
		if _, ok := seen[fieldName]; ok {
			continue
		}
		seen[fieldName] = struct{}{}
		suffix := frontendKeySuffix(fieldName)
		enumRuntime := frontendEnumRuntime{
			FieldName:       fieldName,
			TextMapVarName:  lowerFirst(fieldName) + "TextMap",
			ResolveFuncName: "resolve" + suffix + "Text",
			EnumItems:       make([]frontendEnumRuntimeItem, 0, len(fieldRuntime.Enum.Values)),
		}
		for _, value := range fieldRuntime.Enum.Values {
			enumRuntime.EnumItems = append(enumRuntime.EnumItems, frontendEnumRuntimeItem{
				Key:     value,
				I18nKey: "enum." + fieldRuntime.Enum.ResourceKey + "." + fieldName + "." + value,
			})
		}
		items = append(items, enumRuntime)
	}
	return items
}
