param(
    [string]$WorkspaceRoot = "D:\GoProjects\XAdmin",
    [string]$ModuleName = "xdev",
    [string]$ServiceName = "xdev",
    [string]$HostProject = "D:\GoProjects\XAdmin\admin",
    [string]$TypeScriptRoot = "D:\GoProjects\XAdmin\admin-ui",
    [string]$SourceRoot = "",
    [string]$ModuleRoot = "",
    [string]$CanonicalConfigPath = "",
    [switch]$SkipDryRun,
    [switch]$SkipTypeScript
)

$ErrorActionPreference = "Stop"

function Resolve-Default {
    param(
        [string]$Value,
        [string]$DefaultValue
    )

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return $DefaultValue
    }
    return $Value
}

function Invoke-Step {
    param(
        [string]$Name,
        [scriptblock]$Action
    )

    Write-Host ""
    Write-Host "==> $Name"
    $global:LASTEXITCODE = 0
    & $Action
    if ($global:LASTEXITCODE -ne 0) {
        throw "$Name failed with exit code $global:LASTEXITCODE"
    }
}

function Sync-CanonicalConfig {
    param(
        [string]$CanonicalPath,
        [string]$TargetPath,
        [string]$TargetModule
    )

    if (-not (Test-Path -LiteralPath $CanonicalPath)) {
        throw "Canonical config not found: $CanonicalPath"
    }

    $content = Get-Content -LiteralPath $CanonicalPath -Raw -Encoding utf8
    $content = [System.Text.RegularExpressions.Regex]::Replace(
        $content,
        '(?m)^module:\s*.+$',
        "module: $TargetModule"
    )
    $content = $content.Replace("$ModuleName/api/gen/", "$TargetModule/api/gen/")

    $targetDir = Split-Path -Parent $TargetPath
    if (-not (Test-Path -LiteralPath $targetDir)) {
        New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    }

    [System.IO.File]::WriteAllText($TargetPath, $content, [System.Text.UTF8Encoding]::new($false))
}

$XkitRoot = Join-Path $WorkspaceRoot "xkit"
$SourceRoot = Resolve-Default $SourceRoot (Join-Path $XkitRoot "examples\$ModuleName")
$ModuleRoot = Resolve-Default $ModuleRoot (Join-Path $HostProject "modules\$ModuleName")
$CanonicalConfigPath = Resolve-Default $CanonicalConfigPath (Join-Path $SourceRoot "$ModuleName-config\$ModuleName.yaml")
$ModuleConfigPath = Join-Path $ModuleRoot "$ModuleName.yaml"
$FrontendApiRoot = Join-Path $TypeScriptRoot "apps\web-antd\src\api\generated\$ServiceName"

Write-Host ""
Write-Host "================ xkit generateModule summary ================"
Write-Host "WorkspaceRoot:      $WorkspaceRoot"
Write-Host "XkitRoot:           $XkitRoot"
Write-Host "SourceRoot:         $SourceRoot"
Write-Host "HostProject:        $HostProject"
Write-Host "ModuleName:         $ModuleName"
Write-Host "ServiceName:        $ServiceName"
Write-Host "ModuleRoot:         $ModuleRoot"
Write-Host "ModuleConfig:       $ModuleConfigPath"
Write-Host "CanonicalConfig:    $CanonicalConfigPath"
Write-Host "TypeScriptRoot:     $TypeScriptRoot"
Write-Host "FrontendApiRoot:    $FrontendApiRoot"
Write-Host "SkipDryRun:         $SkipDryRun"
Write-Host "SkipTypeScript:     $SkipTypeScript"
Write-Host "FrontendMeta:       generated by xkit gen module"
Write-Host "============================================================"

Push-Location $XkitRoot
try {
    if (-not $SkipDryRun) {
        Invoke-Step "Preview module source import" {
            go run .\cmd\xkit init module $SourceRoot `
                --project $HostProject `
                --module-name $ModuleName `
                --module-root $ModuleRoot `
                --service $ServiceName `
                --config $ModuleConfigPath `
                --typescript-project $TypeScriptRoot `
                --force `
                --dry-run
        }
    }

    Invoke-Step "Import module source" {
        go run .\cmd\xkit init module $SourceRoot `
            --project $HostProject `
            --module-name $ModuleName `
            --module-root $ModuleRoot `
            --service $ServiceName `
            --config $ModuleConfigPath `
            --typescript-project $TypeScriptRoot `
            --force
    }

    Invoke-Step "Apply canonical module config" {
        Sync-CanonicalConfig `
            -CanonicalPath $CanonicalConfigPath `
            -TargetPath $ModuleConfigPath `
            -TargetModule ("admin/modules/" + $ModuleName)
    }

    Invoke-Step "Generate API Go code" {
        Push-Location (Join-Path $ModuleRoot "api")
        try {
            buf generate --template buf.gen.yaml
        } finally {
            Pop-Location
        }
    }

    Invoke-Step "Generate OpenAPI document" {
        Push-Location (Join-Path $ModuleRoot "api")
        try {
            buf generate --template buf.xdev.openapi.gen.yaml
        } finally {
            Pop-Location
        }
    }

    if (-not $SkipTypeScript) {
        Invoke-Step "Generate TypeScript API code" {
            Push-Location (Join-Path $ModuleRoot "api")
            try {
                buf generate --template buf.vue.xdev.typescript.gen.yaml
            } finally {
                Pop-Location
            }
        }
    }

    Invoke-Step "Prepare dependencies before Ent generation" {
        Push-Location $HostProject
        try {
            go mod tidy
        } finally {
            Pop-Location
        }
    }

    Invoke-Step "Generate Ent code" {
        Push-Location $ModuleRoot
        try {
            go run -mod=mod entgo.io/ent/cmd/ent generate .\data\schema --feature privacy,sql/upsert,sql/versioned-migration,sql/modifier
        } finally {
            Pop-Location
        }
    }

    if (-not $SkipDryRun) {
        Invoke-Step "Preview xkit gen module" {
            go run .\cmd\xkit gen module $ModuleName $ServiceName `
                --project $HostProject `
                --module-root $ModuleRoot `
                --config $ModuleConfigPath `
                --typescript-project $TypeScriptRoot `
                --dry-run
        }
    }

    Invoke-Step "Generate module backend code and frontend meta" {
        go run .\cmd\xkit gen module $ModuleName $ServiceName `
            --project $HostProject `
            --module-root $ModuleRoot `
            --config $ModuleConfigPath `
            --typescript-project $TypeScriptRoot
    }
}
finally {
    Pop-Location
}
