package scaffold

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestApplyTemplateRendersModuleBeforeShortName(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
variables:
  module: xkit-template-v01
  app_name: XAdmin
  command_name: xkit-template
  service_name: admin
ignore:
  - .git/**
preserve:
  - go.mod
`)
	writeTestFile(t, filepath.Join(templateRoot, "go.mod"), "module xkit-template-v01\n")
	writeTestFile(t, filepath.Join(templateRoot, "cmd", "server", "wire.go"), `package main

import _ "xkit-template-v01/internal/server/providers"
`)
	writeTestFile(t, filepath.Join(templateRoot, "cmd", "server", "server.go"), `package main

const commandName = "xkit-template"
`)

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Module:       "example.com/demo",
		AppName:      "DemoAdmin",
		CommandName:  "demo-admin",
		ServiceName:  "admin",
		GeneratedAt:  time.Date(2026, 4, 30, 23, 34, 19, 0, time.FixedZone("CST", 8*60*60)),
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 3 {
		t.Fatalf("written file count mismatch: got %d want 3", len(result.Written))
	}

	wireFile := readTestFile(t, filepath.Join(projectRoot, "cmd", "server", "wire.go"))
	if !strings.HasPrefix(wireFile, "// Code generated from: "+filepath.Base(templateRoot)+".\n// generated at        2026-04-30 23:34:19 CST.\n\n") {
		t.Fatalf("template source header was not added: %s", wireFile)
	}
	if !strings.Contains(wireFile, `"example.com/demo/internal/server/providers"`) {
		t.Fatalf("module import was not rewritten correctly: %s", wireFile)
	}
	if strings.Contains(wireFile, "demo-admin-v01") {
		t.Fatalf("module was rewritten with short command name: %s", wireFile)
	}

	serverFile := readTestFile(t, filepath.Join(projectRoot, "cmd", "server", "server.go"))
	if !strings.Contains(serverFile, `"demo-admin"`) {
		t.Fatalf("command name was not rewritten: %s", serverFile)
	}
}

func TestApplyTemplateDoesNotDoubleReplaceAppNameLiteral(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
variables:
  app_name: Admin
  command_name: xkit-template
`)
	writeTestFile(t, filepath.Join(templateRoot, "cmd", "server", "main.go"), `package main

var (
	Name = "Admin"
	CommandName = "xkit-template"
)
`)

	_, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		AppName:      "MyAdmin",
		CommandName:  "my-admin",
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}

	content := readTestFile(t, filepath.Join(projectRoot, "cmd", "server", "main.go"))
	if !strings.Contains(content, `Name = "MyAdmin"`) {
		t.Fatalf("app name was not replaced correctly: %s", content)
	}
	if strings.Contains(content, "MyMyAdmin") {
		t.Fatalf("app name was replaced twice: %s", content)
	}
	if !strings.Contains(content, `CommandName = "my-admin"`) {
		t.Fatalf("command name was not replaced correctly: %s", content)
	}
}

func TestApplyTemplateSkipsGeneratedHeaderForAlreadyGeneratedGoFile(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
`)
	writeTestFile(t, filepath.Join(templateRoot, "internal", "server", "rest_register.gen.go"), `// Code generated by xkit template placeholder. DO NOT EDIT.

package server
`)

	_, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		GeneratedAt:  time.Date(2026, 4, 30, 23, 34, 19, 0, time.FixedZone("CST", 8*60*60)),
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}

	content := readTestFile(t, filepath.Join(projectRoot, "internal", "server", "rest_register.gen.go"))
	if strings.Contains(content, "Code generated from:") {
		t.Fatalf("already generated Go file received an extra template header: %s", content)
	}
}

func TestApplyTemplateSkipsExistingFilesByDefault(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
variables:
  module: xkit-template-v01
`)
	writeTestFile(t, filepath.Join(templateRoot, "README.md"), "from template\n")
	writeTestFile(t, filepath.Join(projectRoot, "README.md"), "existing\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Module:       "example.com/demo",
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 0 || len(result.Skipped) != 1 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}

	content := readTestFile(t, filepath.Join(projectRoot, "README.md"))
	if content != "existing\n" {
		t.Fatalf("existing file was overwritten: %q", content)
	}
}

func TestApplyTemplateAnnotatesExistingTemplateGoFileWithoutOverwritingBody(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
`)
	filePath := filepath.Join("internal", "server", "manual_http.go")
	writeTestFile(t, filepath.Join(templateRoot, filePath), "package server\n\nconst fromTemplate = true\n")
	writeTestFile(t, filepath.Join(projectRoot, filePath), "package server\n\nconst existing = true\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		GeneratedAt:  time.Date(2026, 4, 30, 23, 34, 19, 0, time.FixedZone("CST", 8*60*60)),
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 1 || len(result.Skipped) != 0 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}

	content := readTestFile(t, filepath.Join(projectRoot, filePath))
	if !strings.HasPrefix(content, "// Code generated from: "+filepath.Base(templateRoot)+".\n// generated at        2026-04-30 23:34:19 CST.\n\n") {
		t.Fatalf("existing Go file was not annotated: %s", content)
	}
	if !strings.Contains(content, "const existing = true") || strings.Contains(content, "const fromTemplate = true") {
		t.Fatalf("existing Go file body was overwritten: %s", content)
	}
}

func TestApplyTemplateRemovesObsoleteFilesWithForce(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
obsolete:
  - cmd/server/wire.go
`)
	writeTestFile(t, filepath.Join(templateRoot, "README.md"), "from template\n")
	obsoletePath := filepath.Join(projectRoot, "cmd", "server", "wire.go")
	writeTestFile(t, obsoletePath, "old wire file\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Force:        true,
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Removed) != 1 {
		t.Fatalf("removed file count mismatch: got %d want 1", len(result.Removed))
	}
	if _, err := os.Stat(obsoletePath); !os.IsNotExist(err) {
		t.Fatalf("obsolete file still exists or unexpected stat error: %v", err)
	}
}

func TestApplyTemplateKeepsPreservedFileEvenWithForce(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
preserve:
  - internal/data/bootstrap/data.go
`)
	dataPath := filepath.Join("internal", "data", "bootstrap", "data.go")
	writeTestFile(t, filepath.Join(templateRoot, dataPath), "package bootstrap\n\n// manual extension point\n")
	writeTestFile(t, filepath.Join(projectRoot, dataPath), "// Code generated by xkit. DO NOT EDIT.\n\npackage bootstrap\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Force:        true,
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 0 || len(result.Skipped) != 1 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}
	content := readTestFile(t, filepath.Join(projectRoot, dataPath))
	if !strings.Contains(content, "Code generated by xkit. DO NOT EDIT.") || strings.Contains(content, "manual extension point") {
		t.Fatalf("preserved generated file should stay project-owned: %s", content)
	}
}

func TestApplyTemplateForceReplacesManualHTTPButKeepsManualHTTPData(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
preserve:
  - internal/server/manual_http_data.go
`)
	manualHTTPPath := filepath.Join("internal", "server", "manual_http.go")
	manualHTTPDataPath := filepath.Join("internal", "server", "manual_http_data.go")
	writeTestFile(t, filepath.Join(templateRoot, manualHTTPPath), "package server\n\nconst fromTemplate = true\n")
	writeTestFile(t, filepath.Join(templateRoot, manualHTTPDataPath), "package server\n\nconst fromTemplateData = true\n")
	writeTestFile(t, filepath.Join(projectRoot, manualHTTPPath), "package server\n\nconst existingManualHTTP = true\n")
	writeTestFile(t, filepath.Join(projectRoot, manualHTTPDataPath), "package server\n\nconst existingManualHTTPData = true\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Force:        true,
		GeneratedAt:  time.Date(2026, 4, 30, 23, 34, 19, 0, time.FixedZone("CST", 8*60*60)),
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 1 || len(result.Skipped) != 1 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}

	manualHTTPContent := readTestFile(t, filepath.Join(projectRoot, manualHTTPPath))
	if !strings.Contains(manualHTTPContent, "const fromTemplate = true") || strings.Contains(manualHTTPContent, "const existingManualHTTP = true") {
		t.Fatalf("manual_http.go was not replaced by template content: %s", manualHTTPContent)
	}

	manualHTTPDataContent := readTestFile(t, filepath.Join(projectRoot, manualHTTPDataPath))
	if !strings.Contains(manualHTTPDataContent, "const existingManualHTTPData = true") || strings.Contains(manualHTTPDataContent, "const fromTemplateData = true") {
		t.Fatalf("manual_http_data.go should stay project-owned: %s", manualHTTPDataContent)
	}
}

func TestApplyTemplateCopiesModuleHostSkeleton(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
variables:
  module: xkit-template-v01
`)
	writeTestFile(t, filepath.Join(templateRoot, "shared", "modulehost", "module.go"), "package modulehost\n\ntype Marker interface{}\n")
	writeTestFile(t, filepath.Join(templateRoot, "internal", "bootstrap", "modules.go"), "package bootstrap\n\nimport _ \"xkit-template-v01/modules\"\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Module:       "example.com/demo",
		GeneratedAt:  time.Date(2026, 6, 20, 0, 0, 0, 0, time.FixedZone("CST", 8*60*60)),
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 2 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}

	moduleHostContent := readTestFile(t, filepath.Join(projectRoot, "shared", "modulehost", "module.go"))
	if !strings.Contains(moduleHostContent, "package modulehost") {
		t.Fatalf("modulehost skeleton was not copied: %s", moduleHostContent)
	}

	modulesContent := readTestFile(t, filepath.Join(projectRoot, "internal", "bootstrap", "modules.go"))
	if !strings.Contains(modulesContent, "_ \"example.com/demo/modules\"") {
		t.Fatalf("bootstrap modules skeleton was not copied: %s", modulesContent)
	}
}

func TestApplyTemplateForceKeepsBootstrapModulesProjectOwned(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
preserve:
  - internal/bootstrap/modules.go
`)
	modulesPath := filepath.Join("internal", "bootstrap", "modules.go")
	writeTestFile(t, filepath.Join(templateRoot, modulesPath), "package bootstrap\n\nimport _ \"xkit-template-v01/modules\"\n")
	writeTestFile(t, filepath.Join(projectRoot, modulesPath), "package bootstrap\n\nimport _ \"project-owned/modules\"\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Force:        true,
		GeneratedAt:  time.Date(2026, 6, 20, 0, 0, 0, 0, time.FixedZone("CST", 8*60*60)),
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 0 || len(result.Skipped) != 1 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}

	modulesContent := readTestFile(t, filepath.Join(projectRoot, modulesPath))
	if !strings.Contains(modulesContent, "project-owned/modules") || strings.Contains(modulesContent, "xkit-template-v01/modules") {
		t.Fatalf("bootstrap modules file should stay project-owned: %s", modulesContent)
	}
}

func TestIsGitTemplateSource(t *testing.T) {
	t.Parallel()

	gitSources := []string{
		"https://github.com/chnxq/xkit-template.git",
		"git@github.com:chnxq/xkit-template.git",
		"ssh://git@github.com/chnxq/xkit-template.git",
		"file:///tmp/xkit-template.git",
	}
	for _, source := range gitSources {
		if !isGitTemplateSource(source) {
			t.Fatalf("source should be detected as git template source: %s", source)
		}
	}

	if isGitTemplateSource(filepath.Join("D:", "GoProjects", "XAdmin", "xkit-template")) {
		t.Fatalf("local directory should not be detected as git template source")
	}
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
