package scaffold

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestApplyTemplateRendersModuleBeforeShortName(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
variables:
  module: xkit-template-v01
  app_name: XAdmin
  command_name: xkit-template
  service_name: admin
ignore:
  - .git/**
preserve:
  - go.mod
`)
	writeTestFile(t, filepath.Join(templateRoot, "go.mod"), "module xkit-template-v01\n")
	writeTestFile(t, filepath.Join(templateRoot, "cmd", "server", "wire.go"), `package main

import _ "xkit-template-v01/internal/server/providers"
`)
	writeTestFile(t, filepath.Join(templateRoot, "cmd", "server", "server.go"), `package main

const commandName = "xkit-template"
`)

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Module:       "example.com/demo",
		AppName:      "DemoAdmin",
		CommandName:  "demo-admin",
		ServiceName:  "admin",
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 3 {
		t.Fatalf("written file count mismatch: got %d want 3", len(result.Written))
	}

	wireFile := readTestFile(t, filepath.Join(projectRoot, "cmd", "server", "wire.go"))
	if !strings.Contains(wireFile, `"example.com/demo/internal/server/providers"`) {
		t.Fatalf("module import was not rewritten correctly: %s", wireFile)
	}
	if strings.Contains(wireFile, "demo-admin-v01") {
		t.Fatalf("module was rewritten with short command name: %s", wireFile)
	}

	serverFile := readTestFile(t, filepath.Join(projectRoot, "cmd", "server", "server.go"))
	if !strings.Contains(serverFile, `"demo-admin"`) {
		t.Fatalf("command name was not rewritten: %s", serverFile)
	}
}

func TestApplyTemplateSkipsExistingFilesByDefault(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
variables:
  module: xkit-template-v01
`)
	writeTestFile(t, filepath.Join(templateRoot, "README.md"), "from template\n")
	writeTestFile(t, filepath.Join(projectRoot, "README.md"), "existing\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Module:       "example.com/demo",
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 0 || len(result.Skipped) != 1 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}

	content := readTestFile(t, filepath.Join(projectRoot, "README.md"))
	if content != "existing\n" {
		t.Fatalf("existing file was overwritten: %q", content)
	}
}

func TestApplyTemplateRemovesObsoleteFilesWithForce(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
obsolete:
  - cmd/server/wire.go
`)
	writeTestFile(t, filepath.Join(templateRoot, "README.md"), "from template\n")
	obsoletePath := filepath.Join(projectRoot, "cmd", "server", "wire.go")
	writeTestFile(t, obsoletePath, "old wire file\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Force:        true,
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Removed) != 1 {
		t.Fatalf("removed file count mismatch: got %d want 1", len(result.Removed))
	}
	if _, err := os.Stat(obsoletePath); !os.IsNotExist(err) {
		t.Fatalf("obsolete file still exists or unexpected stat error: %v", err)
	}
}

func TestApplyTemplateOverwritesGeneratedPreservedFileWithForce(t *testing.T) {
	templateRoot := t.TempDir()
	projectRoot := t.TempDir()

	writeTestFile(t, filepath.Join(templateRoot, "template.yaml"), `name: test
kind: service-template
version: 0.1.0
preserve:
  - internal/data/bootstrap/data.go
`)
	dataPath := filepath.Join("internal", "data", "bootstrap", "data.go")
	writeTestFile(t, filepath.Join(templateRoot, dataPath), "package bootstrap\n\n// manual extension point\n")
	writeTestFile(t, filepath.Join(projectRoot, dataPath), "// Code generated by xkit. DO NOT EDIT.\n\npackage bootstrap\n")

	result, err := ApplyTemplate(TemplateOptions{
		TemplateRoot: templateRoot,
		ProjectRoot:  projectRoot,
		Force:        true,
	})
	if err != nil {
		t.Fatalf("apply template: %v", err)
	}
	if len(result.Written) != 1 || len(result.Skipped) != 0 {
		t.Fatalf("unexpected result: written=%d skipped=%d", len(result.Written), len(result.Skipped))
	}
	content := readTestFile(t, filepath.Join(projectRoot, dataPath))
	if strings.Contains(content, "Code generated by xkit") || !strings.Contains(content, "manual extension point") {
		t.Fatalf("generated preserved file was not replaced with template content: %s", content)
	}
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
